### ISSUE TITLE
sed can't find mirrorlist.

### ISSUE THREAD

**Issue by jlmess77** [sdrausty/TermuxArch#110]
sed can't find mirrorlist because somewhere in the script created double root.$arch directories.

```
📲sed: /data/data/com.termux/files/home/arch/root.x86_64/etc/pacman.d/mirrorlist: No such file or directory
sed: /data/data/com.termux/files/home/arch/root.x86_64/etc/pacman.d/mirrorlist: No such file or directory
```

```
$ find ../../ -name mirrorlist -type f
../../home/arch/root.x86_64/root.x86_64/etc/pacman.d/mirrorlist
```

**Comment by sdrausty** [comment]
This issue is currently resolved.  The path error has to do with the directory structure in the system image file.  This is the case with both x86 and x86_64.  An attempt to resolve this without bsdtar failed.  These changes are reversed, and bsdtar is still required for these two architectures.  Thank you for sharing.
