### ISSUE TITLE
Alert!!! Issues founded.

### ISSUE THREAD

**Issue by nxd84** [sdrausty/TermuxArch#114]
When i am running the command " bash setupTermuxArch.sh " , error comes.
I also tried the command " bash setupTermuxArch.sh refresh " but the error same.
I gave the error's screenshot.
Thank you for support.
![screenshot_20180824-105151](https://user-images.githubusercontent.com/42072272/44566735-cf4d2680-a78c-11e8-8d45-dd9fe4714a73.png)

**Comment by sdrausty** [comment]
@nxd84 more information is requested:
1)  What is the error?
2) What is the result from `bash setupTermuxArch.sh sysinfo`?

**Comment by nxd84** [comment]
Here is the sysinfo-
[setupTermuxArchSysInfo7476.log](https://github.com/sdrausty/TermuxArch/files/2318588/setupTermuxArchSysInfo7476.log)

**Comment by nxd84** [comment]
Here the script completely stopped. I can't install ArchLinux.

![screenshot_20180825-073642](https://user-images.githubusercontent.com/42072272/44613958-a8006300-a839-11e8-940c-c43ff5caeb87.png)

**Comment by sdrausty** [comment]
@nxd84 have you tried `bash setupTermuxArch.sh help`?  Help has instructions how to deal with system image download issues.

**Comment by nxd84** [comment]
I tried but can not fix it.
I gave the ' bash setupTermuxArch.sh help ' command's screenshot. Please give me some suggestions.
![screenshot_20180825-174214](https://user-images.githubusercontent.com/42072272/44618165-43bbbe80-a88e-11e8-9d66-5bee0e55a142.png)
![screenshot_20180825-174221](https://user-images.githubusercontent.com/42072272/44618166-4e765380-a88e-11e8-810a-1f091b5d1adb.png)

**Comment by sdrausty** [comment]
Before exploring the `bash setupTermuxArch.sh manual ` option, see whether `bash setupTermuxArch.sh wget` helps with the curl error.

**Comment by nxd84** [comment]
By running " bash setupTermuxArch.sh wget " ArchLinux is installed.
But after installing when give the command "pacman -Syu" some error came.
I gave screenshot of the error.
![screenshot_20180825-182512](https://user-images.githubusercontent.com/42072272/44618504-ae6ff880-a894-11e8-93c3-24f61aff2d72.png)

**Comment by sdrausty** [comment]
@nxd84 try again.  There is a shortcut command `pci` that you can use to update the databases and install packages; `pc package` installs packages without updating the databases.  You should not be having this error since you installed from this local mirror, and I just checked via web browser that it is currently online.  If necessary, edit /etc/pacman.d/mirrorlist and use a different mirror.

**Comment by abicorios** [comment]
It is nice option to uncomment several mirrors, so it try one, next, next, next...
Edit this file `/etc/pacman.d/mirrorlist`, # simbol comments line, del # simbol to uncomment line with = simbol.

**Comment by sdrausty** [comment]
@darkgeek are the mirrors that you are using in Asia too?  Wget is now set as default. 

https://unix.stackexchange.com/questions/175946/why-is-a-mirror-list-important-for-my-arch-installation

**Comment by darkgeek** [comment]
@sdrausty Yes, I'm from Asia too. It is OK now after your setting wget as default. Thanks.

**Comment by sdrausty** [comment]
@darkgeek you are welcome.

> It is OK now after your setting wget as default. 

Since this is a curl issue (probably with Asian character sets), upstream at https://github.com/curl/curl/issues and https://github.com/termux/termux-packages/issues?q=is%3Aissue+curl are the best places to continue this topic.

Information about mirrors:
https://unix.stackexchange.com/questions/175946/why-is-a-mirror-list-important-for-my-arch-installation
https://wiki.archlinux.org/index.php/Installation_guide#Select_the_mirrors
