### ISSUE TITLE
curl: bad/illegal/missing URL

### ISSUE THREAD

**Issue by jeffrey562** [SDRausty/TermuxArch#178]
After having to manually symlink 3 things, I got this message.
![Screenshot_20190728-153408_Termux](https://user-images.githubusercontent.com/32993574/62073629-1a7a7f80-b20f-11e9-9a18-f7dddd0967d2.jpg)

**Comment by SDRausty** [comment]
You have some options at this point.
1. Use a different download tool.
2. Use `bash setupTermuxArch.sh manual` as the message stated.
3. Use both of the above options.
4. Reinstall Termux, and check if the symlinks from busybox installed correctly.

**Comment by SDRausty** [comment]
> After having to manually symlink 3 things

You should not need to symlink from busybox manually. As busybox is a Termux package, busybox issues are at https://github.com/termux/termux-packages/issues this link.

**Comment by mpolidori** [comment]
@SDRausty I just want to clarify, in case it's another issue. Everything worked fine for me about a week ago. I installed arch without issues. After messing around with it for a bit, I decided to start from scratch. I uninstalled Arch then it wouldn't reinstall due to the sha512sum mismatch. The weird thing is that my version of Termux is from 5/26. It hasn't updated since it was working. I'm not sure what could have broken without an update. I have tried clearing cache/data, reinstalling. I have tried the manual install of arch, different download tool, I tried recreating symlinks (which resulted in having to symlink sha512sum, tar, and uname, like @jeffrey562), none of which solved it. If you still think it's on their end, I'll open an issue.

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break compatibility in Termux.

**Comment by webdavis** [comment]
@jeffrey562 hi, I added `wget` to the end of the command, as in:

    bash setupTermuxArch.sh wget

and the package downloaded and unpacked just fine.

You'll notice when reading through  `setupTermuxArch.sh` that the script accepts other downloaders if you append them to the command.

**Comment by patrickelectric** [comment]
why is this issue closed ? curl is still broken.
```
 🕛 > 🕞 Contacting worldwide mirror https://os.archlinuxarm.org: DONE  

.  If contact with the local mirror is not successful, run setupTermuxArch.sh again.  Should the worldwide mirror not provide another geographically nearby server after a couple of attempts, use setupTermuxArch.sh manual after locating a local mirror from the Internet; See setupTermuxArch.sh help for additional options.  Download of ArchLinuxARM-aarch64-latest.tar.gz pending Internet connection:

curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
```

It did the installation with aria2, but since curl is broken I believe that this issue should be open until it's fixed.

**Comment by SDRausty** [comment]
@patrickelectric https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+curl

> did the installation with aria2

One of reasons TermuxArch uses many download managers is because Termux publishes packages in stable which work, but sometimes do not.  Their motivation appears to be, "It's broken. Root it!" while it should simplify work on device as intended.  If you plan to contribute to https://github.com/termux prepare to be banned for asking intelligent questions.

**Comment by SDRausty** [comment]
@patrickelectric https://github.com/termux/termux-packages/issues?q=is%3Aissue+is%3Aopen+curl

> did the installation with aria2

One of reasons [TermuxArch](https://github.com/TermuxArch) uses many download managers is because Termux publishes packages in stable which work, but sometimes do not.  Their motivation appears to be, "It's broken. Root it!" while it should simplify work on device as intended.  If you plan to contribute to https://github.com/termux prepare to be banned for asking intelligent questions such as device timings.  Maybe their attitude will change in the future.
