### ISSUE TITLE
Can links be opened in the system browser?

### ISSUE THREAD

**Issue by xdrie** [SDRausty/TermuxArch#213]
Base termux provides ~
`termux-open`, can I interface with that?

**Comment by lypanov** [comment]
My local hack to get this working has been to ssh back to localhost and call termux-open. I've also created a termux-open.desktop file in my user XDG application folders such that gnome GUI applications open links in my Android default browser.

**Comment by sudomain** [comment]
clever use of ssh to use termux-open. Termux-api commands such as termux-open can be accessed by editing the `proot` command in startarch (see my comment [here](https://github.com/termux/termux-api/issues/140#issuecomment-605500089). I'm hoping to simplify this process with a PR to this project pending a reply to this [comment](https://github.com/SDRausty/TermuxArch/issues/36#issuecomment-605506554)

**Comment by sudomain** [comment]
@xdrie @lypanov recent commits in [TermuxArch/TermuxArch](https://github.com/TermuxArch/TermuxArch) allow for using termux-api commands such as `termux-open`

**Comment by lypanov** [comment]
> @xdrie @lypanov recent commits in [TermuxArch/TermuxArch](https://github.com/TermuxArch/TermuxArch) allow for using termux-api commands such as `termux-open` in TermuxArch

Weirdly while eg termux-toast works for me termux-open does not. I just get "am: not found".

**Comment by SDRausty** [comment]
This is being re-implemented for the second time:
> declare -a PRFXTOLS	# declare array for device tools that should be accessible in the PRoot environment
PRFXTOLS=**(am getprop toolbox toybox)**	# patial implementaion : system tools that work and can be found can be added to this array

It was dropped twice due to serious errors which impeded the functioning of this installation and configuration script. @lypanov @sudomain @xdrie can you please share what other commands should be added to this array?  

Suggestions are welcome about how this feature should be re-implanted. If you are not worried about collisions and other possible issues, simply add Termux PATH to .bash_profile, and you will get the commands you want from Termux in the PRoot environment.

**Comment by SDRausty** [comment]
Linking is an option to using PATH.  For example command `ln -s /data/data/com.termux/files/usr/bin/termux-open` issued in `~/bin` will give `termux-open` in the PRoot environment.  This is why I'm asking:
> what other commands should be added?

I don't use all the commands.  Really I don't.  One of the reasons is there is too many of them.  This doesn't mean I don't want you to use the command that you want to use.  When I don't know the name of the command that you wish to use it makes it difficult to implement this command into the configuration and installation script.  Please share the names of the Android and Termux commands you would like to have included.

**Comment by lypanov** [comment]
I've for now simply linked am into /usr/local/bin and this works around my issues. I'm personally fine with using the full termux path manually. As such, for me at the very least: Documentation is all I'd need.

**Comment by SDRausty** [comment]
> using the full termux path

If you would like to see how this affects the system in a negative way.  Try this command developed in August 2020; `makeyay` && `yay pikaur` with Termux development tools also installed in the same smartphone. More than likely `makeyay` && `yay pikaur` will not succeed.

**Comment by lypanov** [comment]
> > using the full termux path
> 
> If you would like to see how this affects the system in a negative way. Try this command developed in August 2020; `makeyay` && `yay pikaur` with Termux development tools also installed in the same smartphone. More than likely `makeyay` && `yay pikaur` will not succeed.

Sorry I was ambigious. I mean, I'm just typing in /data/data in all places I need termux-( scripts.

**Comment by SDRausty** [comment]
> typing in /data/data in all places

See if trying a for loop like this one; `for i in $(find /data/data/com.termux/files/usr/bin/ -name "termux*") ; do ln -s $i ; done` will help in typing.  Let the `for` builtin command do the typing for you.

**Comment by sudomain** [comment]
@SDRausty please do not ping (aka github 'mention') my username via `@sudomain` for TermuxArch. As I said in the other issue, I've switched from TermuxArch to proot-distro since they essentially do the same thing (atleast for my purposes). Since I no longer use TermuxArch, I'd appreciate if I didn't get periodic emails because I was pinged on an issue.

**Comment by SDRausty** [comment]
> functioning of this installation and configuration script. @lypanov @xdrie can you please share what other commands should be added to this array?

>> PRFXTOLS=(am getprop toolbox toybox) # patial implementaion : system tools that work and can be found can be added to this array

>> **what other commands should be added to this array?**

**Comment by SDRausty** [comment]
> for i in $(find /data/data/com.termux/files/usr/bin/ -name "termux*") ; do ln -s $i ; done 

Thank you for sharing @lypanov 😃:
```
 need termux-*
```

**Comment by SDRausty** [comment]
Your requests are not yet implemented; in the meantime please enjoy `bash ~/storage/downloads/setupTermuxArch o` : matrix : 

![Screenshot_20200908-203250](https://user-images.githubusercontent.com/27742457/92540409-7d13bc80-f212-11ea-8bf6-a6d49b23b73c.png)

Screenshot from the most recent developments at https://github.com/TermuxArch/TermuxArch/issues/25  this issue request attention.  The current question in this issue is:

>>> **what other commands should be added to this array?**

**Comment by SDRausty** [comment]
`PRFXTOLS=(am getprop termux-* toolbox toybox)`

**Comment by SDRausty** [comment]
I find this this topic and your comments very inspiring.  You may want to try what I'm trying right now:

1. Open a Fail-Safe session,
1. `:/data/data/com.termux/files/home $ echo $PATH > tmp.PATH`,
1. exit # then in new session,
1. `echo "PATH=$(cat tmp.PATH):$PATH" >> .bash_profile`,
1. Open a new session and test the system.

I'm enjoying learning what this change does; How about you?  Are you enjoying the change too?  Please share your findings here.

**Comment by SDRausty** [comment]
https://www.reddit.com/r/termux/comments/ipod6z/what_termux_and_system_commands_work_well_with/

> What Termux and system commands work well with Termux: API? I'd like to know which ones are the most fun to use? Also I'd like to know which ones give the most interesting results. Can you share this with me please?

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature; cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.

**Comment by xdrie** [comment]
I tried it and it seems to work! Thanks!

**Comment by SDRausty** [comment]
> I tried it and it seems to work! Thanks!

@xdrie thank you very much for confirming Libreoffice works on smartphone!

**Comment by SDRausty** [comment]
@xdrie this commit https://github.com/TermuxArch/TermuxArch/commit/10db9b36bf99dd061635eed0c40ee9f7912fa54b dropped `termux-open` support as it did not pass testing.  Can you check if adding it again resolve this issue?

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/33c875f65c7ca8553c3aa3cf573d0fcb634b19f2 adds temporary developer support for these commands @xdrie: 
[`PRFXTOLS=(am dpkg getprop termux-change-repo termux-info termux-open termux-open-url termux-wake-lock termux-wake-unlock)`](https://github.com/SDRausty/TermuxArch/commit/33c875f65c7ca8553c3aa3cf573d0fcb634b19f2#diff-96e6fc14454e2d4bf496fc2de0323d87R838) 

In order to access these commands, you can use the option `setupTermuxArch o`.  Diagnostic information will be helpful to improve this installation script.

**Comment by Ape** [comment]
I tried using `setupTermuxArch o`, but when I try to run the commands I this this error:
```
CANNOT LINK EXECUTABLE "/system/bin/app_process": library "libnativeloader.so" not found: needed by main executable
```

Is this a known issue?

**Comment by SDRausty** [comment]
Which command did you run to get this error?
