### ISSUE TITLE
Termux Arch Linux  please make a GitHub for arm device

### ISSUE THREAD

**Issue by mackrinku** [sdrausty/TermuxArch#22]

**Comment by mackrinku** [comment]
Some issue for installing arch linux in termux...in arm device please make a github for arm device.... please help me

**Comment by mackrinku** [comment]
Modify termux arch linux for arm device...

**Comment by Soph1a7** [comment]
you're not remotely giving any kind of details and/or explanation for your "issue".
arm is already well supported as is by this script.

**Comment by sdrausty** [comment]
@mackrinku submit more information regarding your issue.  We have absolutely no idea how to help you with the information you have given us. @Soph1a7 politely asked you for more information regarding the topic you have opened.  Please see https://sdrausty.github.io/TermuxArch/docs/ISSUE_TEMPLATE.md regarding useful information that should be submitted to resolve an issue asap.  Including a screenshot like the one below can also be very helpful in resolving an issue easily.  
![screenshot_20171123-225157](https://user-images.githubusercontent.com/27742457/33194888-2342b0e8-d0a1-11e7-976b-d2b093d4b101.png)

**Comment by mackrinku** [comment]
What can i do in this process please help me...

**Comment by mackrinku** [comment]
What can i do in this process please help me

**Comment by sdrausty** [comment]
@mackrinku `setupTermuxArch.sh` now creates debugging information will this commit https://github.com/sdrausty/TermuxArch/commit/97feef4ef1b40df1c4453bc6ca0fbce585d1de9c  Run `setupTermuxArch.sh debug` and post this information along with what your issue is about to reopen this issue.  If you think a screenshot with help in resolving your affairs, please include it in your post.  

![screenshot_20171124-153836](https://user-images.githubusercontent.com/27742457/33223452-90796922-d12d-11e7-9099-fc00762c5e99.png)

**Comment by sdrausty** [comment]
Armv7 output:

![screenshot_2017-11-26-04-02-25](https://user-images.githubusercontent.com/27742457/33238575-a29db838-d25e-11e7-89f0-feff3f3e6d6e.png)
