### ISSUE TITLE
Audio (Pulseaudio) support

### ISSUE THREAD

**Issue by LeapofAzzam** [SDRausty/TermuxArch#225]
Outside Arch Linux, Pulseaudio working properly. I can get aound from mpv (which is require Pulseaudio). But, in some case, the audio is not working inside ArchLinux.

**Comment by HoshiYamazaki** [comment]
For me its working, I run XServer SDL and I redirect Audio from Arch.

I just ran Firefox, played some J-Pop music and had no-problem at all (beside Firefox being laggy due to CPU non-llvmpipe sw render).

**Comment by LeapofAzzam** [comment]
I use VNC, and audio isn't working

**Comment by petkar** [comment]
[This](https://www.reddit.com/r/termux/comments/edqe02/comment/fbju8gq) did the job for me. Install pulseaudio in termux and arch.
```
Install package pulseaudio in Termux and configure it to listen on TCP:

pulseaudio --start --exit-idle-time=-1

pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

In chroot execute:

export PULSE_SERVER=127.0.0.1
```

**Comment by SDRausty** [comment]
> This did the job for me. Install pulseaudio in termux and arch.

@petkar thank for sharing!  Please consider submitting a pull request to this [`archlinuxconfig.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash) file and other files if you need too.

**Comment by JanuszChmiel** [comment]
I can confirm this behaviour. PUlseaudio on Termux is working ammzingly even with VLC media player and Gnome-mplayer and also with Firefox or Seamonkey. Important!!!

One of Arch Linux repos for AArch64 contain perfect Seamonkey without shared memory support, somebody around Aur community have recoded The app or reconfigured its build so no shared memory is required. So Android users can even use Seamonkey app with ArchLinux with no issues at all. All build in  Seamonkey functions are working including sound support.

**Comment by SDRausty** [comment]
@JanuszChmiel you are mentioning applications users might want to install; Can you please share some of the `pacman -S` commands that you are using?

**Comment by JanuszChmiel** [comment]
Ofcourse dear MR Rausty and others.
Here are my favourite apps.
pacman -S tigervnc
pacman -S mate mate-extra orca espeak-ng pulseaudio pulseaudio-alsa
Pulseaudio-alsa is extremely important, because you can use build in sound
effects for Mate only with this package.
Many apps can use Pulseaudio-alsa to play sound by using Pulseaudio for
Termux.

And if I want to use X11vnc with some Xorg variant of server I can type.

pacman -S xorg-server-xvfb
Xinit and xorg
pacman -S xorg xorg-xinit 
pacman -S x11vnc
To use xinit it is necessary to use special variant of /etc/X11/xorg.conf

https://gist.github.com/divinity76/ce210b5dbcd9ea7d0585ac403caef577

**Comment by JanuszChmiel** [comment]
It is also necessary to install xterm when using Xinit and Xorg and may be
even when using tigervnc
so
pacman -S xterm
And here are my favourite initialisations commands to start Tigervnc with no
need to type password.

vncserver -kill :0
vncserver -localhost -geometry 1024x768 -depth 24 -name remote-desktop :0
-SecurityTypes=None -extension MIT-SHM
I wqill send special option which will disable remote access by using The
Internet so no password will not mean so big security issues.

**Comment by JanuszChmiel** [comment]
Every body can also install seamonkey
pacman -S seamonkey
And important vnserver option to prevent Internet exposed devices to be
hacked over VNC protocol is to specify
-localhost
command line option. In this case, Xvnc server accepts only localhosts.
Sure, it is possible to create secure passwords or SSH tunels. But I do not
use SSH tunel since my device with strange Android kernel is slow enough so
I do not want to add other slowdowns to The communication.
It is also necessary to mention, that AUr ArchLinux repo contain many many
pkg scripts to install for X86 X64 Intel compatible CPUS. But many of those
packages do not work can not be installed on ArchLinux AArch64. 
I will do my best to build so many pkg based packages for Aarch64 as
possible.
But I would had to have some tool to download all .pkg files and compare
which packages are not part of ArchLinux Aarch64 compatible repositoryes
which MR Rausty have configured to his wonderful ArchLinux installation
scripts.

Shortwave is very probably The most complex app to build. There are many
conflicts betwween versions of used libraryes.
And latest unstable can not work with Libhandy library. I Am getting error
of The Libhandy library, that some GUI element can not be created. SOmething
with cell.
Flatpak will never work with Termux and Proot. SOmebody would had to create
slim ArchLinux kernel which would only contain Bus connection support so app
could connect to Bus by using Kerrnel which would run on A separate Termux
process by using QQemu.
But it would be too complex to reduce The kernel and recompile it.
The next problem is, if it would be possible to make userspace chroot which
would cooperate with ArchLinux kernel which would run by using Qemu for
Android. Very probably not, it would be a strange mix which would be never
supported by none of available Linux distributions.

Mr Pliush have created Alpinetermux. It uses special Qemu for ANdroid,
whichhave been prepared by MR Pliush as a .so library.
Text output from Qemu is not shown by using SDL or other similar library,
data are send to Termux and Termux contain accessibility Java code so I can
read even kernel messages.
Unfortunately, Qemu which emulates hardware is very slow. I would had to
have A rooted Android phone which would contain Kqemu kernel driver compiled
to The Android kernel. In this case, Qemu would work very fast and
efficiently.
But because it is complex, Proot is still The most realistic approach to get
speed and with no need to risk phone bricking.

**Comment by JanuszChmiel** [comment]
If somebody would like to automate ArchLinux, preinstall Mate, Orca and
other sound related stuff, The good source code where it is possible to
begin is to find Debian no root.
Unfortunately, some Git repos are locked so it is complex to rebuild Debian
no root from source. But in conjunction with Pelia it would be possible to
create ArchLinux with Mate preinstalled or with LXDE.
In this case, X11 session with a opportunity to use terminal for working
with Linux commands could attrac more people to ArchLinux and Linux distros
on Android in general.
