### ISSUE TITLE
`keys` broken

### ISSUE THREAD

**Issue by petkar** [SDRausty/TermuxArch#246]
It exits with an error when `keys` is run or when attempting to refresh the installation. Here's the log : 
```
==> Running TermuxArch keys archlinux-keyring archlinuxarm-keyring ca-certificates-utils 2.0.443...
mv: missing file operand
Try 'mv --help' for more information.

 TermuxArch WARNING:  Generated script signal 1 near or at line number 101 by !


TermuxArch keys archlinux-keyring archlinuxarm-keyring ca-certificates-utils 2.0.443: DONE 🏁
```

**Comment by SDRausty** [comment]
@petkar I thank you for sharing so quickly.  There are a number of things that I find surprising about this issue:
1) After thorough testing, that this error crops up after it is published.
2) I did not receive notification of this issue through email.
3) A line of code `mv usr/lib/gnupg/scdaemon{,_} 2>/dev/null ||:` that was thought to be essential for years turns out completely irrelevant at present.  This line of code that was commented out just now with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit was essential to get keys to work a couple of years ago.  The offending culprit that kept this fact hidden from us are these symbols `||:`of code.
4) Excessive latency during the commits to fix this error was also found.  This commit [774406095 on 20200828](https://github.com/TermuxArch/TermuxArch/commit/b2c1a7033b00b12d5aa9186a552a0c06405ee0da) at TermuxArch/TermuxArch was stuck for almost an hour until the next two commits 45 minutes later, essentially empty commits 45 minutes later seem to have pushed the desired commit that fixes this error to be published, as it was not showing up.   The commit in question seemed to have disappeared for a period of time, almost an hour.

This commit is finally migrated to this repository here, and this error is now finally fixed with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit.  I will be analyzing this in detail, and hopefully remedial action will be found so this does not occur again in the future.

**Comment by SDRausty** [comment]
> I did not receive notification of this issue through email.

Something woke me up in the middle of the night last night @petkar.  I recall it was a bad dream about the programs I am publishing.  As I mentioned, I checked my email.  Found nothing regarding this issue. And then I checked the notifications from GitHub.  That is when I noticed this issue.   

This fragment of code makes testing the installation easier `mkdir ~/arch; cp ~/ArchLinuxARM-armv7-latest.tar.gz* ~/arch/`.   The variable KEEP in file [`knownconfigurations.bash`](https://github.com/SDRausty/TermuxArch/blob/master/knownconfigurations.bash) when changed to 0 will keep the downloaded image files instead of deleting them for reuse.  These can be saved and used again on subsequent installs when testing the install feature to lower the bandwidth requirements when testing installing the installation.

**Comment by SDRausty** [comment]
A revision in this line of code `mv usr/lib/gnupg/scdaemon{,_} 2>/dev/null ||:` created this issue.   This issue at https://github.com/termux/proot/issues/10 was thought to be essential for years.  After testing it is completely irrelevant at present.  This line of code was commented out with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit **was essential to get `keys` to work a couple of years ago**.  Basically, this line of code enabled the creation of `keys` back then.  The offending culprit that kept the fact this line of code is obsolete and hidden from us are these symbols `||:`of code.

This commit is now migrated to this repository here, and this error is now fixed with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit.  I will be analyzing this issue in detail, and hopefully remedial action will be found so events like this do not occur again in the future.

This fragment of code makes testing the installation easier `mkdir ~/arch; cp ~/ArchLinuxARM-armv7-latest.tar.gz* ~/arch/`.   The variable KEEP in file [`knownconfigurations.bash`](https://github.com/SDRausty/TermuxArch/blob/master/knownconfigurations.bash#L14) when changed to 0 will keep the downloaded image files instead of deleting them for reuse.  These can be saved and used again on subsequent installs when testing the install feature.  This lowers the bandwidth requirements when testing the  install feature.  Thank you for opening this issue @petkar.

**Comment by SDRausty** [comment]
A recent revision in this line of code `mv usr/lib/gnupg/scdaemon{,_} 2>/dev/null ||:` helped created this issue.   This issue at https://github.com/termux/proot/issues/10 was thought to be essential for years to enable `keys` to function. After testing this line is obsolete.  This line of code was commented out with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit **was essential to get `keys` to work a couple of years ago**.  Basically, this line of code enabled the creation of `keys` back then.  The offending culprit that kept the fact this line of code is obsolete and hidden from us are these symbols `||:`of code.

This error is resolved with this https://github.com/SDRausty/TermuxArch/commit/b3c3a7c37b8a8c7b6ce0097c93fe852a5eb88910 commit.  Thank you for opening this issue @petkar. 

This fragment of code makes testing the installation easier `mkdir ~/arch; cp ~/ArchLinuxARM-armv7-latest.tar.gz* ~/arch/`.   The variable KEEP in file [`knownconfigurations.bash`](https://github.com/SDRausty/TermuxArch/blob/master/knownconfigurations.bash#L14) when changed to 0 will keep the downloaded image and md5 files instead of deleting them for reuse.  These root file system image and md5 files can be saved and used again on subsequent installs when testing the install feature.  Copying these files lowers the Internet bandwidth requirement when testing the  install feature.
