### ISSUE TITLE
Use Rootfs Tarball to Install Arch

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#258]
Hey @SDRausty how to install TermuxArch using Cached Tarball. so i don't have to download arch linux over and over again. which is useful for experiment stuff. and i don't have to wait for downloading an rootfs tarball when reinstalling. sorry for any inconveniences. if i ask too noobish

**Comment by SDRausty** [comment]
> so i don't have to download arch linux over and over again. 

Thank you for sharing @WMCB-Tech; FILE `knownconfigurations.bash`:
`KEEP=1                  ##  change to 0 to keep downloaded image;  Testing the installation process repeatedly can be made easier and lighter on your Internet bandwith and SAR with this fragment of code  'mkdir ~/arch; cp ~/ArchLinux*.tar.gz* ~/arch/'.  The variable KEEP when changed to 0 will keep the downloaded image and md5 files instead of deleting them for later reuse if desired.  The root file system image and md5 files can be saved and used again on subsequent installs when testing the install feature with this and similar fragments of code.`  Rxjoy!

**Comment by SDRausty** [comment]
> so i don't have to download arch linux over and over again. 

Thank you for sharing @WMCB-Tech:

FILE `knownconfigurations.bash` || COMMAND `setupTermuxArch manual`:
1. `KEEP=1                  ##  change to 0 to keep downloaded image;  Testing the installation process repeatedly can be made easier and lighter on your Internet bandwith and SAR with this fragment of code  'mkdir ~/arch; cp ~/ArchLinux*.tar.gz* ~/arch/'.  The variable KEEP when changed to 0 will keep the downloaded image and md5 files instead of deleting them for later reuse if desired.  The root file system image and md5 files can be saved and used again on subsequent installs when testing the install feature with this and similar fragments of code.`  

COMMAND `setupTermuxArch h`:
1. `[./path/systemimage.tar.gz [customdir]]  Install directory argument is optional.  Network install can be substituted by copying systemimage.tar.gz and systemimage.tar.gz.md5 files with 'setupTermuxArch ./[path/]systemimage.tar.gz' and 'setupTermuxArch /absolutepath/systemimage.tar.gz'.`                                                                                                                
1. `[systemimage.tar.gz [customdir]]  Install directory argument is optional.  Network install can be substituted by copying systemimage.tar.gz and systemimage.tar.gz.md5 files with 'setupTermuxArch systemimage.tar.gz'.`

Enjoy!

**Comment by WMCB-Tech** [comment]
Thank you very much @SDRausty.

**Comment by SDRausty** [comment]
You are welcome @WMCB-Tech; feel free to close this issue.
