### ISSUE TITLE
aapt in TermuxArch

### ISSUE THREAD

**Issue by stephenljk** [sdrausty/TermuxArch#31]
Hi there, first of all thank you for such a wonderful port of ArchLinux. I am currently trying to convert cheap affordable tablet into teaching computer for under privilege kids in my neighborhood. I have so far manage to install nodejs as well as postgres database to teach basic HTML scripting, however I am stuck when I tried to use Cordova to build hybrid app.

After installing Cordova, I use the cordova build command, however I can't get it pass the aapt 

![screen shot 2018-01-08 at 4 42 09 pm](https://user-images.githubusercontent.com/4903469/34663696-fb3720f0-f492-11e7-9010-7ba38d3f0141.png)

Since the error says it cannot execute aapt, I tried manually running aapt and this is the result:

![screen shot 2018-01-08 at 4 44 48 pm](https://user-images.githubusercontent.com/4903469/34663760-52a83068-f493-11e7-9373-204b328c0390.png)

I assumed the aapt is not compiled for my armv7, so I installed aapt in termux, copied it and try running it TermuxArch. aapt is able to execute in termux, but it failed again in TermuxArch:

![screen shot 2018-01-08 at 4 48 20 pm](https://user-images.githubusercontent.com/4903469/34663849-d90df598-f493-11e7-99c3-649b8af57f60.png)

At this point in time I am stuck. Can you shine some light on how to get aapt running in TermuxArch? Thanks.

Regards,

Stephen

**Comment by sdrausty** [comment]
You are welcome; and thank you for posting this issue.

> aapt is not compiled for my armv7

Correct.  The reason behind this issue is that `gradle` downloads files for the wrong architecture.  

> installed aapt in termux, copied it and try running it TermuxArch

Both architecture and operating system should match for most packages to work.  Especially when these packages contain binary files like `aapt`. 

> I am stuck

I appears that everyone on arm devices without the knowhow is stuck.  The lucky ones with x86-64 devices are not it seems, and appear to have the green light for `gradle` builds on device at present.  Trying to build https://aur.archlinux.org/packages/android-sdk/ in Arch Linux Termux PRoot on device only confirmed the issue we have encountered.  The error message from building android-sdk on device states **not available for armv7**. There should be a solution https://github.com/sdrausty/buildAPKs/issues/3 for "Gradle Builds..." available for everyone today.  

The course to take for arm device users appears to be to build the APK in Arch Linux Termux PRoot using `gradle` as far as possible.  Then:

*First;* Identify the dependencies after downloading via `gradle`.  Which `jar` files and similar are needed to create the APK.  
*Second;* Modify https://raw.githubusercontent.com/sdrausty/buildAPKs/master/scripts/build/buildOne.sh the build script to include these dependencies to build directly in Termux on Android, Chromebook and Fire OS.

Run this modified build script from [`~/buildAPKs`](https://sdrausty.github.io/buildAPKs/) to build and sign the APK.  Termux in Termux was successfully created in summer 2017 on device with a similar method!  Enjoy building your project.  [Building Android in Termux](https://wiki.archlinux.org/index.php/Android) should be a natural spinoff from this thread.

**Comment by stephenljk** [comment]
Dear Sdrausty,

Thanks for the feedback, I have retried as you suggest. I install aapt in
Termux, then copied the aapt into a folder "android". I am able to execute
the aapt in that folder:

[image: Inline image 1]

However when I tried it in TermuxArch I am having the same error as
previous:

[image: Inline image 4]

The file command already indicated it is compiled in Arm. Please take note
that I have to add a bash in front of ./aapt. Is that what cause the
problem? My apologies, I am not well verse in Linux  environment, still a
learning process for me. Appreciate if you can shine a light and point me
to the right direction. Or if you have time on your hands (and maybe find
it easier) to just give me a fix so I won't spam this thread 😅 I would be
very grateful. Thanks again.

Regards,

Stephen

**Comment by sdrausty** [comment]
@stephenljk Thank you for your response.  Evidently I did not make myself clear enough.  You cannot run most Termux debs in Arch Linux Termux PRoot. Arch Linux uses an emulated kernel.  Termux uses the system kernel.  

This part is done in Arch Linux Termux PRoot.
> First; Identify the dependencies after downloading via gradle. Which jar files and similar are needed to create the APK.

This part is done in straight Termux using buildAPKs.
> Second; Modify https://raw.githubusercontent.com/sdrausty/buildAPKs/master/scripts/build/buildOne.sh the build script to include these dependencies to build directly in Termux on Android, Chromebook and Fire OS.

Run a modified `buildOne.sh` to include the libraries gradle downloaded in the directory with AndroidManifest.xml should produce the desired result in straight Termux.  

Use part one in **Arch Linux Termux PRoot** to get the libraries. 
Do part two in straight **Termux** to include these libraries in the build.

**Comment by tomty89** [comment]
> Arch Linux uses an emulated kernel. Termux uses the system kernel.

Nope, unless by "emulated kernel" you mean proot. You don't even need the kernel because you aren't booting to a system. `pacman -Rs linux-aarch64` might be the first thing you want to do, before the very first `pacman -Syu`.

They do uses different C libraries and so though.

**Comment by sdrausty** [comment]
Issue closed because it does not concern setupTermuxArch itself.
