### ISSUE TITLE
Can I have access to termux api ? like termux-sms-inbox from arch

### ISSUE THREAD

**Issue by sae13** [sdrausty/TermuxArch#36]
hi there . can I have access to termux apis from arch bash?

**Comment by LaChirla** [comment]
**Similar** question here:

sdrausty pointed me in:
https://github.com/termux/termux-packages/issues/2031
to TermuxArch. I gave it a try. It's quite impressing, runs out of the box.

Question:
How can I access android?
I tried androids /system/bin/am and the am from termux.
Both fails.
Thanks

**Comment by sdrausty** [comment]
Thank you both for this inspirational topic.  https://github.com/termux/termux-api/issues should be a good place to expand on this question in the meantime.

**Comment by sdrausty** [comment]
This issue is closed since it does not concern [`setupTermuxArch.sh`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) itself.

**Comment by sdrausty** [comment]
Commit https://github.com/sdrausty/TermuxArch/commit/f16c27d4336ff6e38e1338e7846adc8843b9c0fc adds Arch Linux IRC channel upstream contact information to the TermuxArch motd and logout.  
> See https://wiki.archlinux.org/index.php/IRC_channel for available Arch Linux IRC channels.

**Comment by sudomain** [comment]
@SDRausty I got trmux:api commands working in termuxarch per [this comment](https://github.com/termux/termux-api/issues/140#issuecomment-605500089). 

A few questions:
1. Will you accept a PR that allows execution of the termux:api commands?

Assuming you will accept the PR:
2. Where is the `startarch` script defined in this repo?
3. Where should exported variabled be defined? how about ~/.bashrc of the root user so that the termux:api commands can be accessed by users created with `addauser`
4.  The termux:api commands are defined in `$PREFIX/bin`. I imagine we'd want to add this to the end of $PATH so that the Arch executables are given higher priority over the Termux executables in `$PREFIX/bin`. Should I change $PATH of the root user at all in my PR?

**Comment by SDRausty** [comment]
What other commands should be added to this array?

PRFXTOLS=(am getprop termux-* toolbox toybox)

@sae13 @LaChirla this topic is presently being discussed at [Can links be opened in the system browser? #213](https://github.com/SDRausty/TermuxArch/issues/213):

> can I have access to termux apis from arch bash?

https://www.reddit.com/r/termux/comments/ipod6z/what_termux_and_system_commands_work_well_with/

> What Termux and system commands work well with Termux: API? I'd like to know which ones are the most fun to use? Also I'd like to know which ones give the most interesting results. Can you share this with me please?
