### ISSUE TITLE
Is there a way to mount usr folder from termux to run termux commands?

### ISSUE THREAD

**Issue by neo-expert** [sdrausty/TermuxArch#42]
I would like to run termux-notificacation from arch-linux. Is it posible?
Thank you very much for this great project!

**Comment by sdrausty** [comment]
@neo-expert You are very welcome!  Which files do you want to run from this folder?  If they are binary files they will not work since they are compiled for android.  Other types of files have a chance of working.  Instructions to access `usr`:
1) `cp ~/arch/startarch .` 
2)  Remove the second and third home string from this file.  Leave the first home string alone.   
3)  `./startarch`
4)  `ls`
The output will be `home usr` and both directories will be assessable including subdirectories.

**Comment by neo-expert** [comment]
Interesting:

[root@localhost bin]# ./termux-notification                                         bash: ./termux-notification: /data/data/com.termux/files/usr/bin/bash: bad interpreter: No such file or directory             [root@localhost bin]#

termux-notification is a bash script...

**Comment by MarkoM2** [comment]
You'll need to change the termux shebang to a normal one.

**Comment by neo-expert** [comment]
The termux-notification script runs the termux-api binary. But when i try to run it from arch:

[13:25 home ]$ ls termux-api
termux-api
[13:26 home ]$ ./termux-api
bash: ./termux-api: No such file or directory
[13:27 home ]$

**Comment by sdrausty** [comment]
@neo-expert the output of `file termux-api` should explain everything.  Try `file` on a file   in `/bin` too for similar information.
