### ISSUE TITLE
Terminal won't return to termux bash after logout

### ISSUE THREAD

**Issue by MarkoM2** [sdrausty/TermuxArch#43]
Sometimes when I logout from aarch, the terminal won't return to the termux bash prompt. All I can do then is to open another terminal and kill the proot process.

![screenshot_20180128-113047](https://user-images.githubusercontent.com/35829869/35481898-f94c9898-042c-11e8-9732-32abe0f69d5e.png)

**Comment by sdrausty** [comment]
@MarkoM2 Can you post the output of `setupTermuxArch.sh --sysinfo`?  See if using Arch Linux in Termux PRoot as non root user helps.  

This issue is closed since it does not concern [`setupTermuxArch.sh`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) itself.  Post links to upstream in this thread.

**Comment by MarkoM2** [comment]
Ok, my fault. It did that, when I had started a crond in arch and didn't kill it before exit. 
I just made an alias which kills the last crond and exits.

**Comment by kevhoo** [comment]
root@localhost:~# exit && bash
