### ISSUE TITLE
Ability for Scripts to Launch Commands for Arch Linux in Termux PRoot on Device

### ISSUE THREAD

**Issue by cherryleafroad** [sdrausty/TermuxArch#54]
Hi,

It would be incredibly useful if scripts had the ability to launch commands in Arch Linux, much the same way you can do a `bash -c`, maybe a `startarch -c`

This would benefit scripts that run from Termux:Boot or Termux:Task

**Comment by sdrausty** [comment]
Hello,

Thank you for your time and insight.  Can you explain this a little bit more?  First, what is the intended outcome?  

> would benefit scripts that run from Termux:Boot or Termux:Task

This is a very good suggestion.  Can you provide some examples?

**Comment by cherryleafroad** [comment]
Sure, let me see if I can explain a little more detailed.

The purpose is so that, from Termux point of view, you can run "access" arch just as if it were another part of the system, being able to run scripts on the arch side, from termux. Since termux has access to the system, this is easy to do, as long as passing commands to it like we do with bash is possible.

So, the outcome is to be able to run Termux scripts as if they were one and the same as arch.

For example, from Termux, I could run `startarch -c "bash script.sh"`, and this would allow me to use archs extensive library of programs. The current way it is, this kind of access isn't available except through direct means (opening the console)

I imagine the implementation to be simple, just pass any commands to arch via `startarch -c "commands"`. A use case even this simple should be more than adequate to do anything

**Comment by tomty89** [comment]
Something like this:
```
$ type alex
alex is a function
alex ()
{
    bash -c "unset LD_PRELOAD; proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w $HOME /usr/bin/env -i HOME=$HOME TERM=$TERM /usr/bin/bash -lc 'cd $PWD; $*'"
}
$ alex archlinux-java status
Available Java environments:
  java-7-openjdk
  java-8-openjdk
  java-9-openjdk (default)
$ alex archlinux-java set java-8-openjdk
$ alex javac -version
javac 1.8.0_111
$ cd a/
$ pwd
/data/data/com.termux/files/home/a
$ ls -l b
total 4
-rw------- 1 u0_a292 u0_a292 183 Mar  9 04:44 test.java
$ alex "cd b; javac test.java"
$ ls -l b
total 8
-rw-r--r-- 1 u0_a292 u0_a292 482 Mar  9 04:46 Alex.class
-rw------- 1 u0_a292 u0_a292 183 Mar  9 04:44 test.java
$ cd b
$ dx --dex --output=test.jar Alex.class
$ dalvikvm -cp test.jar Alex
Does Alex sound cool?
This is just a demo. Termux does have ecj
$ alex java Alex
Does Alex sound cool?
This is just a demo. Termux does have ecj
$
```

**Comment by tomty89** [comment]
It would work better as a script since `$PWD` and `$*` can be properly quoted when the commands are inheritly run in a sub-shell:
```
$ type alex
alex is a function
alex ()
{
    bash -c "unset LD_PRELOAD; exec proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w $PWD /usr/bin/env -i HOME=$HOME TERM=$TERM /usr/bin/bash -lc '$*'"
}
$ cat $HOME/alex
unset LD_PRELOAD
exec proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w "$PWD" /usr/bin/env -i HOME=$HOME TERM=$TERM /usr/bin/bash -lc "$*"
$ mkdir a\ b
$ $HOME/alex "cd a\ b; pwd"
/data/data/com.termux/files/home/a b
$ alex "cd a\ b; pwd"
/data/data/com.termux/files/home/a b
$ $HOME/alex 'cd "a b"; pwd'
/data/data/com.termux/files/home/a b
$ alex 'cd "a b"; pwd'
/data/data/com.termux/files/home/a b
$ $HOME/alex "cd 'a b'; pwd"
/data/data/com.termux/files/home/a b
$ alex "cd 'a b'; pwd"
b; pwd: line 0: cd: a: No such file or directory
$ cd a\ b/
$ $HOME/alex pwd
/data/data/com.termux/files/home/a b
$ alex pwd
proot warning: can't chdir("/data/data/com.termux/files/home/a/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: 'b' not found (root = /data/data/com.termux/files/arch, cwd = /, $PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets)
fatal error: see `proot --help`.
$
```

**Comment by tomty89** [comment]
Some might prefer this:
```
$ cat ./alex-umask
#!/data/data/com.termux/files/usr/bin/sh
unset LD_PRELOAD
exec proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w "$PWD" /usr/bin/env -i HOME=$HOME TERM=$TERM /usr/bin/bash -lc "umask $(umask); $*"
$ ls -l a b
ls: cannot access 'a': No such file or directory
ls: cannot access 'b': No such file or directory
$ ./alex touch a
$ ./alex-umask touch b
$ ls -l a b
-rw-r--r-- 1 u0_a292 u0_a292 0 Mar  9 07:06 a
-rw------- 1 u0_a292 u0_a292 0 Mar  9 07:06 b
$ ./alex mkdir c
$ ./alex-umask mkdir d
$ ls -ld c d
drwxr-xr-x 2 u0_a292 u0_a292 4096 Mar  9 07:07 c
drwx------ 2 u0_a292 u0_a292 4096 Mar  9 07:07 d
$
```

**Comment by sdrausty** [comment]
Options have been introduced to `startarch`  https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L215&L249 thanks to this issue.  They are `-c`, `-l` (--login) and `-r` (--raw).  

Does option `-c` fulfill the requirement for resolution @cherryleafroad?  What is the long form for `-c`?

@tomty89 thank you for participating and expanding upon this issue.  

Use `addauser` or `addauserps` before using `startarch --login username args`.  For example: `addauser newuser` in Arch Linux in Termux PRoot will create user `newuser`.  Then in a new Termux session `startarch --login newuser -c ~/echo.sh args1` should fulfill the request with the addition of running the command a normal user (in this example `newuser`) in Arch Linux in Termux PRoot as opposed to the root account which should only be used for system maintenance.

**Comment by sdrausty** [comment]
@cherryleafroad 
> This would benefit scripts that run from Termux:Boot or Termux:Task

Can you provide some examples?  This does sound useful.

**Comment by sdrausty** [comment]
> Forgive the beginner question, but how do I update the script when arch is already installed?

Thank you for your question.  Thanks to your request one more enhancement has just been implemented with this https://github.com/sdrausty/TermuxArch/commit/4615d7e504bf622bb990ff6f01850f7119090217 commit.  `setupTermuxArch.sh --refresh` should do what you want it to do now as well as `startarch --command`.  

```
$ cat ./arch/startarch
#!/data/data/com.termux/files/usr/bin/bash -e
# Copyright 2017-2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Hosting https://sdrausty.github.io/TermuxArch courtesy https://pages.github.com
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
# https://sdrausty.github.io/TermuxArch/README has information about this project.
################################################################################
unset LD_PRELOAD
# [command args] Execute a command in BASH as root.
if [[ $1 = [Cc]* ]] || [[ $1 = -[Cc]* ]] || [[ $1 = --[Cc]* ]];then
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch/ -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="xterm-256color" PS1='[termux@arch \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash -lc $@ ||:
# [login user|su user] || [login user -c command|su user -c command] Login as user.  Alternatively, login as user and execute command.  Use `addauser user` first to create this user and the user home directory
elif [[ $1 = [Ll]* ]] || [[ $1 = -[Ll]* ]] || [[ $1 = --[Ll]* ]] || [[ $1 = [Ss]* ]] || [[ $1 = -[Ss]* ]] || [[ $1 = --[Ss]* ]];then
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch/ -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="xterm-256color" PS1='[termux@arch \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/su - ${@:2} ||:
# [raw args] Construct the `startarch` proot statement.  For example `startarch r su - archuser` will login as user archuser.  Use `addauser archuser` first to create this user and the user home directory.
elif [[ $1 = [Rr]* ]] || [[ $1 = -[Rr]* ]] || [[ $1 = --[Rr]* ]];then
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch/ -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="xterm-256color" PS1='[termux@arch \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/$@ ||:
else
# [] Default Arch Linux in Termux PRoot root login.
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch/ -b /dev/ -b /sys/ -b /proc/ -b /storage/ -b /data/data/com.termux/files/home -w /data/data/com.termux/files/home /bin/env -i HOME=/root TERM="xterm-256color" PS1='[termux@arch \W]$ ' LANG=en_US.UTF-8 PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/bash --login ||:
fi
```

**Comment by tomty89** [comment]
You don't want `-w $HOME` but `-w $PWD` especially for the direct execute ones, because otherwise when you cd to somewhere else and try to work on files there, you will fail coz proot keep looking files in $HOME. and $PWD should be double-quoted in case of spaces or so in it.

And you need a **double-quoted** `$*` instead of `$@`, because `bash -lc` wants a single word:
```
$ cat test.sh
for i in $@; do
    echo $i;
done

for i in "$@"; do
    echo $i;
done

for i in $*; do
    echo $i;
done
for i in "$*"; do
    echo $i;
done
$ ./test.sh a b c
a
b
c
a
b
c
a
b
c
a b c
$
```

You at least want `HOME=$HOME` for direct execution, because of various reasons, like expansion of the command line passed (`~` / `$HOME`, and maybe even shell history or so. For a shell `$HOME` or `/root` it's more of preference.

And you always want the login shell (`-l`) even when you want to direct execute a command because you want the proper env vars in being set by /etc/profile`, including LANG and PATH. We should never have hardcoded these, especially for PATH (coz it's not always just `/usr/bin/path` and its symlink variants). So the third one (`/bin/$@`) should go. It's silly to hardcode `PS1` as well. (I remember it didn't even work).

**Comment by tomty89** [comment]
@sdrausty oh for your question
```
$ printenv ANDROID_DATA
/data
$ printenv EXTERNAL_STORAGE
/sdcard
$
```
I use these instead of `-b $HOME` and `-b /storage` respectively.

**Comment by barre121** [comment]
Greetings!
Guys, i have arch installed for days and i haven't  done
anything with it because of my short knowledge of it.
I wanted was to grab some pentesting tools from it's
repo play with them. 
like these once:

Metasploit, 
routersploit
Empire,
beEF
Vega
Maltego,
NMap, 
wifite

I run 

Pacman -Su routersploit.

Says terget not found.


They say edit by adding:

 /etc/pacman.conf and add:

[archstrike]

Server = https://mirror.archstrike.org/$arch/$repo

[blackarch]

Server = http://blackarch.org/blackarch/$repo/os/$arch

Next run pacman -Syu to update your repository listing. To install either distribution, run one of these commands:

pacman -S archstrike –needed

pacman -S blackarch –needed

If that is so
I copy this and  then where in the file  should i past?


Can't i grab these tools without adding and installing 
these big sized distros?


help please!
i don't know  where to start.

**Comment by sdrausty** [comment]
@tomty89 awesome advice with details.  Thank you.  TermuxArch v.1.2 is available for testing and should meet all the requirements of this topic.

**Comment by tomty89** [comment]
Well you are still using `$@`, and got `-b /proc` removed when it should stay, and all those unnecessary hard coded env vars, and variants should be added and removed...

Should I be glad that you at least got `-w` right? I am definitely glad that I am capable of writing the appropriate script myself though...

**Comment by tomty89** [comment]
Geez `$HOME$rootdir`? I don't know what's rootdir but can't you even put the slash betwewn the variables instead of in `$rootdir`, just to make it read/look better.

`LANG=$LANG` is the most hilarious one because in Termux LANG will only be en_US.UTF-8, not to mention there's no reason to set LANG/PATH here.

**Comment by sdrausty** [comment]
@tomty89 compare `startarch -l user -c top` with `@` and `*`.  `*` doesn't work.

`@` works for `startarch -l user -c top`:
`exec proot --kill-on-exit --link2symlink -0 -r $HOME/arch/ -b /dev/ -b $ANDROID_DATA -b $EXTERNAL_STORAGE -b /proc/ -w "$PWD" /bin/env -i HOME=/root TERM=$TERM LANG=$LANG PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/su - "${@:2}"`

`*` does not:
`exec proot --kill-on-exit --link2symlink -0 -r $HOME/arch/ -b /dev/ -b $ANDROID_DATA -b $EXTERNAL_STORAGE -b /proc/ -w "$PWD" /bin/env -i HOME=/root TERM=$TERM LANG=$LANG PATH=/bin:/usr/bin:/sbin:/usr/sbin /bin/su - "${*:2}"`

Can any of these `proot` statements be dropped?  Ideas how to get `startarch -l user -c top -v` to load correctly are welcome 🎼🎵🎶✏🗒

**Comment by tomty89** [comment]
I already told you:
```
su - $2
su - $2 -c "${*:3}"`
```
Whether to have su variants is your choice. I don't think it's necessary coz in my experience faking as normal user in proot with `su` is only problematic. You rarely want to do it anyway. You may only do the first/shell one and not the second/direct execute one as well.

And this variant should be dropped totally:
```
/bin/$@
```

And please please please drop the setting of LANG because it prevents `/etc/profile.d/locale.sh` (`-z $LANG`) from setting it to value in `/etc/locale.conf`. Please get to know Arch.

**Comment by tomty89** [comment]
The reason `top` worked is because it ddidn't take any argument, Like in my tests `echo` "worked" for both quoted and unquoted `$@` and unquoted `$*`, it's just that they only print the default newline but not `a b c` as for quoted `$*`.

**Comment by tomty89** [comment]
```
$ cat ../usr/bin/alarm
#!/data/data/com.termux/files/usr/bin/sh
unset LD_PRELOAD
exec proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w /root /usr/bin/env -i HOME=/root TERM=$TERM /usr/bin/bash -l
$ alarm
[root@localhost ~]# printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
[root@localhost ~]# printenv LANG
en_US.UTF-8
[root@localhost ~]# cat /etc/locale.conf
LANG=en_US.UTF-8
[root@localhost ~]# cat -h
cat: invalid option -- 'h'
Try 'cat --help' for more information.
[root@localhost ~]# echo 'LANG=es_ES.UTF-8' > /etc/locale.conf
[root@localhost ~]# logout
$ alarm
[root@localhost ~]# printenv LANG
es_ES.UTF-8
[root@localhost ~]# cat /etc/locale.conf
LANG=es_ES.UTF-8
[root@localhost ~]# cat -h
cat: opción inválida -- 'h'
Pruebe 'cat --help' para más información.
[root@localhost ~]#
```

**Comment by tomty89** [comment]
```
$ cat ../usr/bin/alex
#!/data/data/com.termux/files/usr/bin/sh
unset LD_PRELOAD
exec proot --link2symlink -0 -b /proc -b /dev -b $ANDROID_DATA -b $EXTERNAL_STORAGE -r $HOME/../arch -w "$PWD" /usr/bin/env -i HOME=/root TERM=$TERM /usr/bin/bash -lc "umask $(umask); $*"
$ alex printenv LANG
en_US.UTF-8
$ alex cat /etc/locale.conf
LANG=en_US.UTF-8
$ alex cat -h
cat: invalid option -- 'h'
Try 'cat --help' for more information.
$ alex "echo 'LANG=es_ES.UTF-8' > /etc/locale.conf"
$ alex printenv LANG
es_ES.UTF-8
$ alex cat /etc/locale.conf
LANG=es_ES.UTF-8
$ alex cat -h
cat: opción inválida -- 'h'
Pruebe 'cat --help' para más información.
$ alex printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
$
```

**Comment by cherryleafroad** [comment]
@sdrausty 
The new script is working perfectly, thank you very much. Here is how I've configured my scripts:

I created a helper run-arch-script.sh
```
#!/data/data/com.termux/files/usr/bin/bash

if [ $# -lt 1 ]; then
    echo Usage: run-arch-script.sh /full/script/path.sh arg1 arg2
    exit
fi

startarch -c "bash $*"
```

In Tasker, use command
File `/sdcard/Tasker/bin/convert-image.sh`
Arguments `/sdcard/Tasker/bin/convert-image.sh %asfile1` (script to execute, and a special variable in Tasker)

Convert-image.sh
```
#!/data/data/com.termux/files/usr/bin/bash

if [ -L $0 ]; then
    cdir=$(dirname $(readlink $0))
else
    cdir=$(dirname $(realpath $0))
fi

# using other clang build so far
#unset LD_PRELOAD
#PATH=$PATH:$HOME/usr/bin
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/usr/lib

border=15
octagon=4
fuzz=3
blur=2x20

magick \( $1 +repage -bordercolor white -border 1x1 \
-fuzz $fuzz% -fill transparent -floodfill +0+0 white -shave 1x1 \
-bordercolor transparent -border ${border}x${border} \) \
\( -clone 0 -fill white -colorize 100% \) \
\( -clone 0 -alpha extract -write mpr:alpha -morphology edgeout octagon:$octagon -write mpr:edge \
mpr:alpha -fill transparent -floodfill +0+0 black \
-compose over -composite \
-fill white -floodfill +0+0 transparent -alpha off -negate \
-fill transparent -floodfill +0+0 black -write mpr:chunk \
mpr:edge -compose dst_over -composite \) \
-alpha off -compose over -composite \
\( mpr:alpha mpr:chunk -compose over -composite \
-morphology dilate octagon:$octagon  \
-blur $blur -level 50x100% \) \
-alpha off -compose copy_opacity -composite -trim  +repage \
$1.gif

touch $cdir/.done
```

**Comment by tomty89** [comment]
For what is worth:
```
$ alarm
[root@localhost ~]# ls -ld /{,usr/}{,s}bin
lrwxrwxrwx 1 root root     7 Dec 10 14:18 /bin -> usr/bin
lrwxrwxrwx 1 root root     7 Dec 10 14:18 /sbin -> usr/bin
drwxr-xr-x 5 root root 24576 Mar  9 20:20 /usr/bin
lrwxrwxrwx 1 root root     3 Dec 10 14:18 /usr/sbin -> bin
[root@localhost ~]#
```
That's why `PATH` set by Arch includes only `/usr/bin`. Please get to know Arch. Just don't hardcode `PATH` in the proot/env command.

**Comment by sdrausty** [comment]
`startarch -r bash -lc pwd && whoami` works with @ not with *. 
Ditto for `startarch -l e -c pwd && whoami --version`.

LANG=$LANG is depreceated; So is $PATH.  Awesome.  Thanks for pointing out the Arch way @tomty89. This makes the `proot` statements leaner, nice.  

@cherryleafroad I am glad to hear that the script is working for you.

**Comment by tomty89** [comment]
Please **read** carefully what I told you **multiple times.

1. Drop the `-r` variant, coz it sucks and is pointless. You don't want to execute Arch program without invoking a login shell. I didn't expect it to be used for this variant anyway. **Just drop this variant.**

2. Do not expect the `-l` variant to accept direct execution. If you want that, implement a separate variant for it. I already told you how **twice** how to do that on posts above. It will be used like this `startarch -x myuser echo hello world`.

3. You simply didn't notice that both of your cases didn't really work. You didn't even know how to test appropriately.

In both cases, you successfully executes Arch's `pwd` because it didn't take any *argument*. Didn't you see I test with `echo a b c` instead of just `echo`?

But you didn't got Arch's whoami executed but Termux's.

When you are passing more than just a command (multiple commands linked with `&&`, `;` or so on; or command line involves redirection / piping), you need to quote the line anyway.

You really want to understand these:
```
$ bash -c echo $$ && echo $$

12943
$ bash -c 'echo $$' && echo $$
12974
12943
$ bash -c "echo $$" && echo $$
12943
12943
$ bash -c 'echo $$ && echo $$'
13033
13033
$ bash -c "echo $$ && echo $$"
12943
12943
$
```

Please at least get to know a bit more about bash before testing inappropriately and saying what "work" and "not work" blindly.

**Comment by tomty89** [comment]
More fun:
```
$ cat meh
bash -c "$1"
bash -c "$@"
bash -c "$*"
$ ./meh whoami
u0_a292
u0_a292
u0_a292
$ ./meh whoami -h
u0_a292
u0_a292
whoami: invalid option -- 'h'
Try 'whoami --help' for more information.
$ ./meh whoami && pwd
u0_a292
u0_a292
u0_a292
/data/data/com.termux/files/home
$ echo false >> meh
$ ./meh whoami && pwd
u0_a292
u0_a292
u0_a292
$ ./meh "whoami && pwd"
u0_a292
/data/data/com.termux/files/home
u0_a292
/data/data/com.termux/files/home
u0_a292
/data/data/com.termux/files/home
$
```

**Comment by sdrausty** [comment]
["The implementation of "\$\*" has always been a problem and realistically should have been replaced with the behavior of "\$\@". In almost every case where coders use "\$\*", they mean "\$\@","](https://github.com/sdrausty/TermuxArch/commit/dd5678aae90386f526e6207a7a9e3c1210288ac2) from https://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_02.html

All the [`exec proot`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/frags/proots.md)  invocations are in one place for study.  Is there any thing else that we might want to discuss @tomty89 about Termux PRoot and how it is being called?

> without invoking a login shell.

Raw is raw, complete control.  Choose the desired shell and options to login.  Default enter can echo usage with examples.

**Comment by tomty89** [comment]
It's pointless to quote random sources while ignoring the context.

The reason why we *need* `"$*"` intead of `"$@"` is because we are not passing multiple arguments as multiple arguments, but multiple arguments as single argument, which is in turn because what we are wrapping is `-c` of `bash`/`su`.

`"$@"` would work if you expect users to always quote the passed command line, but in that case you don't even need `"$@"` but "`$2`" or so, because the quoted command line is *a* single argument.

While `"$*"` allows the wrapper to work like `sudo`, where quoting is only needed in certain cases.

> Raw is raw, complete control. Choose the desired shell and options to login.

No. Complete control is write your own start/execute script (more of "line" actually). The raw variant you are having could only miss lead people to think that it could be safely used for executing any program in Arch, while it is not because you need a login shell to set all the env vars for you (except the one we hardcoded with `env`).

If you want a non-root execute variant, then write a specifc one for that, `$2` is username and `'$3"` or `"$*"` is the command line passed.

And you "example" is still wrong. You always need to quote the command line passed to `-c` when it consists of more than one command, no matter if a wrapper is involved or if it uses `"$@"` or `"$*"`, so it should be:

```
startarch raw su - newuser -c "pwd && whoami"
```

Otherwise you will be running `pwd` in Arch proot and `whoami` in Termux.

**Comment by sdrausty** [comment]
@tomty89 was notified with this https://github.com/termux/termux-packages/pull/2306#issuecomment-381747690 regarding the contributions made by that account.

> @tomty89 I don't want your broken ideas anymore https://github.com/sdrausty/TermuxArch/commit/1660e3664fe009be4351d91fca38e4a8609510a0  

```
+#### [tomty89](https://github.com/tomty89) has been banned from contributing anymore to this and similar projects for the following reasons: badgering to infuse tainted code, professing falsehoods as fact, and reversing on and deleting relevant comments for development of this project. 
```
References:
1) **Using $\* can introduce security holes according to sources.**
2) https://github.com/sdrausty/TermuxArch/issues/30#issuecomment-375092877
3) https://github.com/tomty89/proot_scripts/issues/1
