### ISSUE TITLE
Shared: NO such file or directory!

### ISSUE THREAD

**Issue by xqdoo00o** [sdrausty/TermuxArch#61]
In Termux, I setup storage and it's all right to access `storage/shared`. 
But when I `startarch`, I only could access `storage`,
if I try to `cd shared` then, I got a warning like the title says.

**Comment by sdrausty** [comment]
@xqdoo00o thank you for posting this recent development.  This is unfortunate.  

> Is it possible that this commit broke shared storage for PRoot?  This issue [shared:No such file or directory #61](https://github.com/sdrausty/TermuxArch/issues/61) just cropped up; and guess what?  Cannot access shared storage on all devices developing TermuxArch as of this commit, possibly a previous one too.  Is this from libraries PRoot uses?

From https://github.com/termux/termux-packages/commit/fbd53df3e4387db96e5e619afdee351983b99db9#commitcomment-28135580

**Comment by tomty89** [comment]
All symlinks set up by `termux-setup-storage` points `/storage/emulated/0`, but in a recent commit in TermuxArch, `-b /storage` has been changed to `-b $EXTERNAL_STORAGE`, which will be expanded to `-b /sdcard`, so in the Arch proot you can only access the internal storage from`/sdcard`, but not its realpath `/storage/emulated/0`.

**Comment by sdrausty** [comment]
While we are at the topic of debugging, output from `bash setupTermuxArch.sh sysinfo` is requested.  This printout will also aid other projects like [au](https://github.com/sdrausty/au) and [buildAPKs](https://github.com/sdrausty/buildAPKs) to name a couple which don't rely on automated system detection  by themselves at present.

@tomty89 thank you for this update.  Adding `-b /storage/emulated/0/` worked on a device just tested.   I shall be looking into this in more detail soon on more devices and architectures.

@xqdoo00o  see whether editing `statarch` helps for now.  Use `cp startarch startarch1` before editing.  When this topic is resolved, `bash setupTermuxArch.sh refresh` will update `startarch` to the newest version/release.  An update is pending soon.

**Comment by tomty89** [comment]
You can really just change it back to `-b /storage`. It was fine to use and I never really I asked you to change that (I only showed a script of mine that uses `-b $EXTERNAL_STORAGE` and told you what if refers to; it's ironic that you mimick that automatically but doesn't fix you bash on `$@` when you told you repeatedly to with insanely detailed explanations).

`/storage` is a more general entry point where can lead you to the mountpoint of a "real" SD card when it exists as well.

I used `-b $EXTERNAL_STORAGE` because:
1. I don't use a real SD card in addition to the internal storage (the emulated SD card)
2. I don't use `termux-setup-storage`
3. I always access the internal storage with the handy `/sdcard` symlink that exists already

But those are personal practice.

`-b /sdcard` and `-b /storage` don't conflict with each other anyway though.

**Comment by tomty89** [comment]
In fact you should probably avoid using the env vars anyway. I found it fancy at a point but it's actually kind of silly and unnecessary. So just do `-b /data -b /storage` or `-b /data -b /storage -b /sdcard` instead of `-b $ANDROID_DATA -b $EXTERNAL_STORAGE`. It will serve you better.

**Comment by sdrausty** [comment]
@xqdoo00o and @tomty89 `exec proot...` is restated time and again, this is being rewritten into a self building code block depending on the environment encountered.  A little more effort, time and work at present should pay off once completed in a number of ways.

A self building PRoot statement that builds itself from the environment it finds itself in will be a timesaver for recoding TermuxArch in the future.  Also, additional options to insert code into the PRoot statement will become possible through both `knownconfigurations.sh` and `bash setupTermuxArch.sh options`.

**Comment by sdrausty** [comment]
>  rewritten into a self building code block 

@xqdoo00o @tomty89 here it is, for your testing pleasure and code review:
```
prs ()
{
prootstmnt="exec proot"
if [ $koe ]; then
	prootstmnt+=" --kill-on-exit"
fi
if [ $kid ]; then
	prootstmnt+=" --kernel-release=4.14.15"
fi
prootstmnt+=" --link2symlink -0 -r $installdir -b $ANDROID_DATA -b /dev/ -b $EXTERNAL_STORAGE -b /sys/ -b /proc/ -b /storage/ -b $HOME -w $HOME /bin/env -i HOME=/root TERM=$TERM"
}
```
It is in [knownconfigurations.sh](https://github.com/sdrausty/TermuxArch/blob/master/knownconfigurations.sh#L68&L78).  Use `bash setupTermuxArch.sh manual` to access the proot statment during install.  It appears that this issue is resolved with added benefits for the user, provided the user understands proot statements.  If you would like this proot statement tweeked, share a comment here.

**Comment by sdrausty** [comment]
@xqdoo00o @tomty89 [thank you for improving TermuxArch.](https://github.com/sdrausty/TermuxArch/commit/81ceba0ede03f9df5a93d8241ef91de3ab285812)

**Comment by tomty89** [comment]
1. As I said, better to use `-b /data -b /sdcard` instead of `-b $ANDROID_DATA -b $EXTERNAL_STORAGE`
2. You don't need `-b $HOME` when there's `-b /data`
3. Order/group the `-b`s for readability, e.g. `-b /proc -/b dev -b /sys -b /data -b /sdcard -b /storage`
4. You cannot have `-w $HOME` as a general option. Use `-w $HOME` for only login variants but `-w $PWD` for direct execution variants
