### ISSUE TITLE
Install Arch Linux in Termux

### ISSUE THREAD

**Issue by shanitarini** [sdrausty/TermuxArch#62]
Mobile Switch off ?

**Comment by sdrausty** [comment]
@shanitarini what is your question?  Do you have a comment?  How are you enjoying Linux on your mobile?

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/f16c27d4336ff6e38e1338e7846adc8843b9c0fc commit adds Arch Linux IRC channel upstream contact information to the TermuxArch motd and logout.

**Comment by sdrausty** [comment]
Issue closed due to inactivity.

Email : termux+subscribe@groups.io
Github : https://github.com/termux/
Gitter : https://gitter.im/termux/termux
Termux Community : https://plus.google.com/communities/101692629528551299417
Try Arch Linux https://github.com/archlinuxarm too. 
https://github.com/ArchStrike/ArchStrike 
https://wiki.archlinux.org/index.php/IRC_channel
