### ISSUE TITLE
What exactly is TermuxArch?

### ISSUE THREAD

**Issue by tnishimura** [sdrausty/TermuxArch#63]
Hi, I found your project through the termux project's java-related issues. My main interest is being able to code clojure from within Termux. 

What exactly does it mean to install Arch within Termux? Does it mean that you made a chrootable environment with the arch package manager available within? If so, is it possible to run applications within it and outside it together? Is there possibility of conflict between anything in TermuxArch and Termux, and if so, how would I uninstall?

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/f16c27d4336ff6e38e1338e7846adc8843b9c0fc commit adds Arch Linux IRC channel upstream contact information to the TermuxArch motd and logout.

**Comment by sdrausty** [comment]
Issue closed due to inactivity.

Email : termux+subscribe@groups.io
Github : https://github.com/termux/
Gitter : https://gitter.im/termux/termux
Termux Community : https://plus.google.com/communities/101692629528551299417
Try Arch Linux https://github.com/archlinuxarm too. 
https://github.com/ArchStrike/ArchStrike 
https://wiki.archlinux.org/index.php/IRC_channel
