### ISSUE TITLE
Pacman -Syu returning 404

### ISSUE THREAD

**Issue by iineo** [sdrausty/TermuxArch#88]
I added one of the mirrors from archlinux32 [https://ind.mirror.archlinux32.org/$arch/$repo]
and pacman -Syy and -Syu are not working with the error "The requested URL returned error: 404". 

EDIT: The commands did work with the previous mirror list.

**Comment by FreshMosh** [comment]
I just checked your link. 
I seems like there is no ARM-Repository on this Mirror. I dont know if Arch32 even has any ARM-support. 
So the quick answer to your Problem is: search for a mirror with arm repo. 

--------
The /$arch/$repo in the URL usualy resolves into something like 
/x86_64/core (in x64 systems) 
or, as in this case
/arm/core 
which does not existiert in this repo.

**Comment by iineo** [comment]
Oooh alright thanks
